platform :ios, '8.0'
use_frameworks!
target :HNBNetWorkDemo do
    pod 'AFNetworking', '3.1.0'
    pod 'HNBNetWork',:path => '../'
    pod 'ReactiveObjC', '3.0.0'
    pod 'MBProgressHUD', '1.0.0'
end
